---
  new_page_extension: md
  auto_deploy: false
  admin_path:
  webhook_url:
  sections:
    - type: directory
      path: _posts # replace this with the relative path to your content section
      label: Posts
      create: documents
      match: "**/*.md"
      new_doc_ext: md
      templates:
        - post # replace this with your template filename name
  upload_dir: public/uploads
  public_path: "/uploads"
  front_matter_path: ""
  use_front_matter_path: false
  file_template: ":filename:"